# Generated by Django 3.1.6 on 2021-02-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20210217_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='Book Title', max_length=50, unique=True),
        ),
    ]
