# Generated by Django 3.1.7 on 2021-02-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20210222_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_published',
            new_name='published',
        ),
    ]
