# Generated by Django 3.1.7 on 2021-02-26 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20210226_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='demo.book'),
        ),
    ]
